name: build-release-binary

run-name: Go Build and Release Binary

on:
  push:
    tags:
      - "v*.*.*"
    branches: [master]
#  pull_request:
#    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    # debug
    - name: Dump env
      run: env | sort
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - run: git version
    - run: git branch
    - run: git tag
    
    # setup
    - name: Set up Go v1.20.4
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20.4
      id: go

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # get all tags, needed to get git log
        ref: master
        
    - name: Go get dependencies
      run: go get -v -t -d ./...

    - name: Go build for Win_x64
      run: |
        go version
#        cd src
#        go mod init ${GITHUB_REPOSITORY}
#        go mod tidy
        GOOS=windows GOARCH=amd64 go build -v -o scoop-search-multisource.exe .

    # release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') && github.repository == 'plicit/scoop-search-multisource'
      with:
        files: |
          scoop-search-multisource.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
