name: build-release-binary

run-name: Go Build and Release Binary

on:
  push:
    tags:
      - "v*.*.*"
    branches: [master]
  pull_request:
    branches: [master]
#  workflow_dispatch:
#    inputs:
#      debug_enabled:
#        type: boolean
#        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
#        required: false
#        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
#    # Enable tmate debugging of manually-triggered workflows if the input option was provided
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
#      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      
    # debug
    - name: Dump env
      run: env | sort
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    # setup
    - name: Set up Go v1.20.4
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20.4
      id: go

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # get all tags, needed to get git log
        ref: master
        
    - name: Go get dependencies
      run: go get -v -t -d ./...
      
    - name: Go build for Win_x64
      run: |
        go version
        GOOS=windows GOARCH=amd64 go build -v -o scoop-search-multisource.exe .
    
    # debug
    - run: git version
    - run: git branch
    - run: git tag
    
    # release
    - name: Release
      uses: softprops/action-gh-release@v1
      # only release if this is a new tag
      if: startsWith(github.ref, 'refs/tags/') && github.repository == 'plicit/scoop-search-multisource'
      with:
        files: |
          scoop-search-multisource.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
